# Generated by Django 2.0.4 on 2018-04-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'Client in CSD', 'verbose_name_plural': 'Clients in CSD'},
        ),
        migrations.AlterField(
            model_name='client',
            name='id_cdb',
            field=models.CharField(help_text='ID in HEAnet ClientDB', max_length=100, verbose_name='ID ClientDB'),
        ),
        migrations.AlterField(
            model_name='client',
            name='id_csd',
            field=models.PositiveIntegerField(help_text='ID in Juniper CSD', verbose_name='ID CSD'),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(help_text='Client name as shown in Juniper CSD', max_length=100, verbose_name='Client name'),
        ),
    ]
