# Generated by Django 2.0.4 on 2018-04-12 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_auto_20180412_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElineLdp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_csd', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('functional_audit', models.CharField(max_length=100)),
                ('configuration_audit', models.CharField(max_length=100)),
                ('fault_status', models.CharField(max_length=100)),
                ('overall_status', models.CharField(max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.Client')),
            ],
        ),
    ]
