# Generated by Django 2.0.4 on 2018-04-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20180415_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fqdn', models.CharField(max_length=100)),
                ('csd_id', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=100)),
                ('meid', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['fqdn'],
            },
        ),
    ]
