# Generated by Django 2.0.4 on 2018-04-16 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_ne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ne',
            old_name='csd_id',
            new_name='id_csd',
        ),
    ]
