# Generated by Django 2.0.4 on 2018-04-17 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0008_servicetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('csd_id', models.PositiveIntegerField()),
                ('state', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=100)),
                ('csd_created', models.DateTimeField()),
                ('csd_updated', models.DateTimeField()),
                ('functional_audit', models.CharField(max_length=100)),
                ('configuration_audit', models.CharField(max_length=100)),
                ('fault_status', models.CharField(max_length=100)),
                ('overall_status', models.CharField(max_length=100)),
                ('service_definition', models.CharField(max_length=100)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.Client')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ServiceType')),
            ],
        ),
    ]
