# Generated by Django 2.0.4 on 2018-04-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0009_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=100)),
                ('interface_index', models.PositiveIntegerField()),
                ('ne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.Ne')),
            ],
            options={
                'verbose_name': 'Service Endpoints',
                'verbose_name_plural': 'Service Endpoints in CSD',
                'ordering': ['ne'],
            },
        ),
    ]
