# Generated by Django 2.0.4 on 2018-04-17 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0010_serviceendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceendpoint',
            name='service',
            field=models.ForeignKey(default=17268865, on_delete=django.db.models.deletion.CASCADE, to='inventories.Service'),
            preserve_default=False,
        ),
    ]
